### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by gajus** [gajus/url-regexp#4]
```
curiosity:url-regexp gajus$ npm run test

> url-regexp@1.1.0 test /Users/gajus/Documents/dev/gajus/url-regexp
> npm run pragmatist test


> url-regexp@1.1.0 pragmatist /Users/gajus/Documents/dev/gajus/url-regexp
> node ./node_modules/.bin/pragmatist "test"

[14:34:05] Starting 'pragmatist:task-pre-copy-clean'...
[14:34:05] Finished 'pragmatist:task-pre-copy-clean' after 5.01 ms
[14:34:05] Starting 'pragmatist:test-copy'...
[14:34:05] Finished 'pragmatist:test-copy' after 22 ms
[14:34:05] Starting 'pragmatist:test-build'...
[14:34:06] Finished 'pragmatist:test-build' after 217 ms
[14:34:06] Starting 'pragmatist:test-hook-require'...
[14:34:06] Finished 'pragmatist:test-hook-require' after 21 ms
[14:34:06] Starting 'pragmatist:test-run'...


  URLRegExp
    .validate()
      ✓ passes http://foo.com/blah_blah
      ✓ passes http://foo.com/blah_blah/
      ✓ passes http://foo.com/blah_blah_(wikipedia)
      ✓ passes http://foo.com/blah_blah_(wikipedia)_(again)
      ✓ passes http://www.example.com/wpstyle/?p=364
      ✓ passes https://www.example.com/foo/?bar=baz&inga=42&quux
      ✓ passes http://✪df.ws/123
      ✓ passes http://userid:password@example.com:8080
      ✓ passes http://userid:password@example.com:8080/
      ✓ passes http://userid@example.com
      ✓ passes http://userid@example.com/
      ✓ passes http://userid@example.com:8080
      ✓ passes http://userid@example.com:8080/
      ✓ passes http://userid:password@example.com
      ✓ passes http://userid:password@example.com/
      ✓ passes http://142.42.1.1/
      ✓ passes http://142.42.1.1:8080/
      ✓ passes http://➡.ws/䨹
      ✓ passes http://⌘.ws
      ✓ passes http://⌘.ws/
      ✓ passes http://foo.com/blah_(wikipedia)#cite-1
      ✓ passes http://foo.com/blah_(wikipedia)_blah#cite-1
      ✓ passes http://foo.com/unicode_(✪)_in_parens
      ✓ passes http://foo.com/(something)?after=parens
      ✓ passes http://☺.damowmow.com/
      ✓ passes http://code.google.com/events/#&product=browser
      ✓ passes http://j.mp
      ✓ passes ftp://foo.bar/baz
      ✓ passes http://foo.bar/?q=Test%20URL-encoded%20stuff
      ✓ passes http://مثال.إختبار
      ✓ passes http://例子.测试
      ✓ passes http://उदाहरण.परीक्षा
      ✓ passes http://-.~_!$&'()*+,;=:%40:80%2f::::::@example.com
      ✓ passes http://1337.net
      ✓ passes http://a.b-c.de
      ✓ passes http://a.b--c.de/
      ✓ passes http://5.0.0.1
      ✓ passes http://5.0.0.254
      ✓ passes http://5.0.125.1
      ✓ passes http://5.0.125.254
      ✓ passes http://5.0.255.1
      ✓ passes http://5.0.255.125
      ✓ passes http://5.0.255.254
      ✓ passes http://25.0.0.1
      ✓ passes http://25.0.0.254
      ✓ passes http://25.0.125.1
      ✓ passes http://25.0.125.254
      ✓ passes http://25.0.255.1
      ✓ passes http://25.0.255.125
      ✓ passes http://25.0.255.254
      ✓ passes http://223.0.0.1
      ✓ passes http://223.0.0.254
      ✓ passes http://223.0.125.1
      ✓ passes http://223.0.125.254
      ✓ passes http://223.0.255.1
      ✓ passes http://223.0.255.125
      ✓ passes http://223.0.255.254
      ✓ passes http://223.125.0.1
      ✓ passes http://223.125.0.254
      ✓ passes http://223.125.125.1
      ✓ passes http://223.125.125.254
      ✓ passes http://223.125.255.1
      ✓ passes http://223.125.255.125
      ✓ passes http://223.125.255.254
      ✓ passes http://223.255.0.1
      ✓ passes http://223.255.0.254
      ✓ passes http://223.255.125.1
      ✓ passes http://223.255.125.254
      ✓ passes http://223.255.255.1
      ✓ passes http://223.255.255.125
      ✓ passes http://223.255.255.254
      ✓ fails http://
      ✓ fails http://.
      ✓ fails http://..
      ✓ fails http://../
      ✓ fails http://?
      ✓ fails http://??
      ✓ fails http://??/
      ✓ fails http://#
      ✓ fails http://##
      ✓ fails http://##/
      ✓ fails http://foo.bar?q=Spaces should be encoded
      ✓ fails //
      ✓ fails //a
      ✓ fails ///a
      ✓ fails ///
      ✓ fails http:///a
      ✓ fails foo.com
      ✓ fails rdar://1234
      ✓ fails h://test
      ✓ fails http:// shouldfail.com
      ✓ fails :// should fail
      ✓ fails http://foo.bar/foo(bar)baz quux
      ✓ fails ftps://foo.bar/
      ✓ fails http://-error-.invalid/
      ✓ fails http://-a.b.co
      ✓ fails http://a.b-.co
      ✓ fails http://0.0.0.0
      ✓ fails http://10.1.1.0
      ✓ fails http://10.1.1.1
      ✓ fails http://10.1.1.125
      ✓ fails http://10.1.1.254
      ✓ fails http://10.1.1.255
      ✓ fails http://10.255.255.255
      ✓ fails http://172.16.0.0
      ✓ fails http://172.16.0.1
      ✓ fails http://172.16.0.254
      ✓ fails http://172.16.0.255
      ✓ fails http://172.16.125.0
      ✓ fails http://172.16.125.1
      ✓ fails http://172.16.125.254
      ✓ fails http://172.16.125.255
      ✓ fails http://172.16.255.0
      ✓ fails http://172.16.255.1
      ✓ fails http://172.16.255.125
      ✓ fails http://172.16.255.254
      ✓ fails http://172.16.255.255
      ✓ fails http://172.24.0.0
      ✓ fails http://172.24.0.1
      ✓ fails http://172.24.0.254
      ✓ fails http://172.24.0.255
      ✓ fails http://172.24.125.0
      ✓ fails http://172.24.125.1
      ✓ fails http://172.24.125.254
      ✓ fails http://172.24.125.255
      ✓ fails http://172.24.255.0
      ✓ fails http://172.24.255.1
      ✓ fails http://172.24.255.125
      ✓ fails http://172.24.255.254
      ✓ fails http://172.24.255.255
      ✓ fails http://172.31.0.0
      ✓ fails http://172.31.0.1
      ✓ fails http://172.31.0.254
      ✓ fails http://172.31.0.255
      ✓ fails http://172.31.125.0
      ✓ fails http://172.31.125.1
      ✓ fails http://172.31.125.254
      ✓ fails http://172.31.125.255
      ✓ fails http://172.31.255.0
      ✓ fails http://172.31.255.1
      ✓ fails http://172.31.255.125
      ✓ fails http://172.31.255.254
      ✓ fails http://172.31.255.255
      ✓ fails http://192.168.1.0
      ✓ fails http://192.168.1.1
      ✓ fails http://192.168.1.125
      ✓ fails http://192.168.1.254
      ✓ fails http://192.168.1.255
      ✓ fails http://192.168.255.0
      ✓ fails http://192.168.255.1
      ✓ fails http://192.168.255.125
      ✓ fails http://192.168.255.254
      ✓ fails http://192.168.255.255
      ✓ fails http://224.1.1.1
      ✓ fails http://1.1.1.1.1
      ✓ fails http://123.123.123
      ✓ fails http://3628126748
      ✓ fails http://.www.foo.bar/
      ✓ fails http://www.foo.bar./
      ✓ fails http://.www.foo.bar./
    .match()
      ✓ matches
      1) does not match
      ✓ matches unique URLs
    .replace()
      ✓ replaces http://foo.com/blah_blah
      ✓ replaces http://foo.com/blah_blah/
      ✓ replaces http://foo.com/blah_blah_(wikipedia)
      ✓ replaces http://foo.com/blah_blah_(wikipedia)_(again)
      ✓ replaces http://www.example.com/wpstyle/?p=364
      ✓ replaces https://www.example.com/foo/?bar=baz&inga=42&quux
      ✓ replaces http://✪df.ws/123
      ✓ replaces http://userid:password@example.com:8080
      ✓ replaces http://userid:password@example.com:8080/
      ✓ replaces http://userid@example.com
      ✓ replaces http://userid@example.com/
      ✓ replaces http://userid@example.com:8080
      ✓ replaces http://userid@example.com:8080/
      ✓ replaces http://userid:password@example.com
      ✓ replaces http://userid:password@example.com/
      ✓ replaces http://142.42.1.1/
      ✓ replaces http://142.42.1.1:8080/
      ✓ replaces http://➡.ws/䨹
      ✓ replaces http://⌘.ws
      ✓ replaces http://⌘.ws/
      ✓ replaces http://foo.com/blah_(wikipedia)#cite-1
      ✓ replaces http://foo.com/blah_(wikipedia)_blah#cite-1
      ✓ replaces http://foo.com/unicode_(✪)_in_parens
      ✓ replaces http://foo.com/(something)?after=parens
      ✓ replaces http://☺.damowmow.com/
      ✓ replaces http://code.google.com/events/#&product=browser
      ✓ replaces http://j.mp
      ✓ replaces ftp://foo.bar/baz
      ✓ replaces http://foo.bar/?q=Test%20URL-encoded%20stuff
      ✓ replaces http://مثال.إختبار
      ✓ replaces http://例子.测试
      ✓ replaces http://उदाहरण.परीक्षा
      ✓ replaces http://-.~_!$&'()*+,;=:%40:80%2f::::::@example.com
      ✓ replaces http://1337.net
      ✓ replaces http://a.b-c.de
      ✓ replaces http://a.b--c.de/
      ✓ replaces http://5.0.0.1
      ✓ replaces http://5.0.0.254
      ✓ replaces http://5.0.125.1
      ✓ replaces http://5.0.125.254
      ✓ replaces http://5.0.255.1
      ✓ replaces http://5.0.255.125
      ✓ replaces http://5.0.255.254
      ✓ replaces http://25.0.0.1
      ✓ replaces http://25.0.0.254
      ✓ replaces http://25.0.125.1
      ✓ replaces http://25.0.125.254
      ✓ replaces http://25.0.255.1
      ✓ replaces http://25.0.255.125
      ✓ replaces http://25.0.255.254
      ✓ replaces http://223.0.0.1
      ✓ replaces http://223.0.0.254
      ✓ replaces http://223.0.125.1
      ✓ replaces http://223.0.125.254
      ✓ replaces http://223.0.255.1
      ✓ replaces http://223.0.255.125
      ✓ replaces http://223.0.255.254
      ✓ replaces http://223.125.0.1
      ✓ replaces http://223.125.0.254
      ✓ replaces http://223.125.125.1
      ✓ replaces http://223.125.125.254
      ✓ replaces http://223.125.255.1
      ✓ replaces http://223.125.255.125
      ✓ replaces http://223.125.255.254
      ✓ replaces http://223.255.0.1
      ✓ replaces http://223.255.0.254
      ✓ replaces http://223.255.125.1
      ✓ replaces http://223.255.125.254
      ✓ replaces http://223.255.255.1
      ✓ replaces http://223.255.255.125
      ✓ replaces http://223.255.255.254
      ✓ replaces multiple urls at once
      ✓ fails http://
      ✓ fails http://.
      ✓ fails http://..
      ✓ fails http://../
      ✓ fails http://?
      ✓ fails http://??
      ✓ fails http://??/
      ✓ fails http://#
      ✓ fails http://##
      ✓ fails http://##/
      2) fails http://foo.bar?q=Spaces should be encoded
      ✓ fails //
      ✓ fails //a
      ✓ fails ///a
      ✓ fails ///
      ✓ fails http:///a
      ✓ fails foo.com
      ✓ fails rdar://1234
      ✓ fails h://test
      ✓ fails http:// shouldfail.com
      ✓ fails :// should fail
      3) fails http://foo.bar/foo(bar)baz quux
      ✓ fails ftps://foo.bar/
      ✓ fails http://-error-.invalid/
      ✓ fails http://-a.b.co
      ✓ fails http://a.b-.co
      ✓ fails http://0.0.0.0
      ✓ fails http://10.1.1.0
      ✓ fails http://10.1.1.1
      ✓ fails http://10.1.1.125
      ✓ fails http://10.1.1.254
      ✓ fails http://10.1.1.255
      ✓ fails http://10.255.255.255
      ✓ fails http://172.16.0.0
      ✓ fails http://172.16.0.1
      ✓ fails http://172.16.0.254
      ✓ fails http://172.16.0.255
      ✓ fails http://172.16.125.0
      ✓ fails http://172.16.125.1
      ✓ fails http://172.16.125.254
      ✓ fails http://172.16.125.255
      ✓ fails http://172.16.255.0
      ✓ fails http://172.16.255.1
      ✓ fails http://172.16.255.125
      ✓ fails http://172.16.255.254
      ✓ fails http://172.16.255.255
      ✓ fails http://172.24.0.0
      ✓ fails http://172.24.0.1
      ✓ fails http://172.24.0.254
      ✓ fails http://172.24.0.255
      ✓ fails http://172.24.125.0
      ✓ fails http://172.24.125.1
      ✓ fails http://172.24.125.254
      ✓ fails http://172.24.125.255
      ✓ fails http://172.24.255.0
      ✓ fails http://172.24.255.1
      ✓ fails http://172.24.255.125
      ✓ fails http://172.24.255.254
      ✓ fails http://172.24.255.255
      ✓ fails http://172.31.0.0
      ✓ fails http://172.31.0.1
      ✓ fails http://172.31.0.254
      ✓ fails http://172.31.0.255
      ✓ fails http://172.31.125.0
      ✓ fails http://172.31.125.1
      ✓ fails http://172.31.125.254
      ✓ fails http://172.31.125.255
      ✓ fails http://172.31.255.0
      ✓ fails http://172.31.255.1
      ✓ fails http://172.31.255.125
      ✓ fails http://172.31.255.254
      ✓ fails http://172.31.255.255
      ✓ fails http://192.168.1.0
      ✓ fails http://192.168.1.1
      ✓ fails http://192.168.1.125
      ✓ fails http://192.168.1.254
      ✓ fails http://192.168.1.255
      ✓ fails http://192.168.255.0
      ✓ fails http://192.168.255.1
      ✓ fails http://192.168.255.125
      ✓ fails http://192.168.255.254
      ✓ fails http://192.168.255.255
      ✓ fails http://224.1.1.1
      4) fails http://1.1.1.1.1
      ✓ fails http://123.123.123
      ✓ fails http://3628126748
      ✓ fails http://.www.foo.bar/
      5) fails http://www.foo.bar./
      ✓ fails http://.www.foo.bar./
      6) does not replace multiple urls at once


  319 passing (124ms)
  6 failing

  1) URLRegExp .match() does not match:

      AssertionError: expected [ Array(4) ] to deeply equal []
      + expected - actual

      -[
      -  "http://foo.bar"
      -  "http://foo.bar/foo(bar)baz"
      -  "http://1.1.1.1"
      -  "http://www.foo.bar"
      -]
      +[]

      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:427:19)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at Context.<anonymous> (.test-build/tests/url-regexp.js:40:86)

  2) URLRegExp .replace() fails http://foo.bar?q=Spaces should be encoded:

      AssertionError: expected 'new-value?q=Spaces should be encoded' to equal 'http://foo.bar?q=Spaces should be encoded'
      + expected - actual

      -new-value?q=Spaces should be encoded
      +http://foo.bar?q=Spaces should be encoded

      at Context.<anonymous> (.test-build/tests/url-regexp.js:81:53)

  3) URLRegExp .replace() fails http://foo.bar/foo(bar)baz quux:

      AssertionError: expected 'new-value quux' to equal 'http://foo.bar/foo(bar)baz quux'
      + expected - actual

      -new-value quux
      +http://foo.bar/foo(bar)baz quux

      at Context.<anonymous> (.test-build/tests/url-regexp.js:81:53)

  4) URLRegExp .replace() fails http://1.1.1.1.1:

      AssertionError: expected 'new-value.1' to equal 'http://1.1.1.1.1'
      + expected - actual

      -new-value.1
      +http://1.1.1.1.1

      at Context.<anonymous> (.test-build/tests/url-regexp.js:81:53)

  5) URLRegExp .replace() fails http://www.foo.bar./:

      AssertionError: expected 'new-value./' to equal 'http://www.foo.bar./'
      + expected - actual

      -new-value./
      +http://www.foo.bar./

      at Context.<anonymous> (.test-build/tests/url-regexp.js:81:53)

  6) URLRegExp .replace() does not replace multiple urls at once:

      AssertionError: expected 'http:// http://. http://.. http://../ http://? http://?? http://??/ http://# http://## http://##/ new-value?q=Spaces should be encoded // //a ///a /// http:///a foo.com rdar://1234 h://test http:// shouldfail.com :// should fail new-value quux ftps://foo.bar/ http://-error-.invalid/ http://-a.b.co http://a.b-.co http://0.0.0.0 http://10.1.1.0 http://10.1.1.1 http://10.1.1.125 http://10.1.1.254 http://10.1.1.255 http://10.255.255.255 http://172.16.0.0 http://172.16.0.1 http://172.16.0.254 http://172.16.0.255 http://172.16.125.0 http://172.16.125.1 http://172.16.125.254 http://172.16.125.255 http://172.16.255.0 http://172.16.255.1 http://172.16.255.125 http://172.16.255.254 http://172.16.255.255 http://172.24.0.0 http://172.24.0.1 http://172.24.0.254 http://172.24.0.255 http://172.24.125.0 http://172.24.125.1 http://172.24.125.254 http://172.24.125.255 http://172.24.255.0 http://172.24.255.1 http://172.24.255.125 http://172.24.255.254 http://172.24.255.255 http://172.31.0.0 http://172.31.0.1 http://172.31.0.254 http://172.31.0.255 http://172.31.125.0 http://172.31.125.1 http://172.31.125.254 http://172.31.125.255 http://172.31.255.0 http://172.31.255.1 http://172.31.255.125 http://172.31.255.254 http://172.31.255.255 http://192.168.1.0 http://192.168.1.1 http://192.168.1.125 http://192.168.1.254 http://192.168.1.255 http://192.168.255.0 http://192.168.255.1 http://192.168.255.125 http://192.168.255.254 http://192.168.255.255 http://224.1.1.1 new-value.1 http://123.123.123 http://3628126748 http://.www.foo.bar/ new-value./ http://.www.foo.bar./' to equal 'http:// http://. http://.. http://../ http://? http://?? http://??/ http://# http://## http://##/ http://foo.bar?q=Spaces should be encoded // //a ///a /// http:///a foo.com rdar://1234 h://test http:// shouldfail.com :// should fail http://foo.bar/foo(bar)baz quux ftps://foo.bar/ http://-error-.invalid/ http://-a.b.co http://a.b-.co http://0.0.0.0 http://10.1.1.0 http://10.1.1.1 http://10.1.1.125 http://10.1.1.254 http://10.1.1.255 http://10.255.255.255 http://172.16.0.0 http://172.16.0.1 http://172.16.0.254 http://172.16.0.255 http://172.16.125.0 http://172.16.125.1 http://172.16.125.254 http://172.16.125.255 http://172.16.255.0 http://172.16.255.1 http://172.16.255.125 http://172.16.255.254 http://172.16.255.255 http://172.24.0.0 http://172.24.0.1 http://172.24.0.254 http://172.24.0.255 http://172.24.125.0 http://172.24.125.1 http://172.24.125.254 http://172.24.125.255 http://172.24.255.0 http://172.24.255.1 http://172.24.255.125 http://172.24.255.254 http://172.24.255.255 http://172.31.0.0 http://172.31.0.1 http://172.31.0.254 http://172.31.0.255 http://172.31.125.0 http://172.31.125.1 http://172.31.125.254 http://172.31.125.255 http://172.31.255.0 http://172.31.255.1 http://172.31.255.125 http://172.31.255.254 http://172.31.255.255 http://192.168.1.0 http://192.168.1.1 http://192.168.1.125 http://192.168.1.254 http://192.168.1.255 http://192.168.255.0 http://192.168.255.1 http://192.168.255.125 http://192.168.255.254 http://192.168.255.255 http://224.1.1.1 http://1.1.1.1.1 http://123.123.123 http://3628126748 http://.www.foo.bar/ http://www.foo.bar./ http://.www.foo.bar./'
      + expected - actual

      -http:// http://. http://.. http://../ http://? http://?? http://??/ http://# http://## http://##/ new-value?q=Spaces should be encoded // //a ///a /// http:///a foo.com rdar://1234 h://test http:// shouldfail.com :// should fail new-value quux ftps://foo.bar/ http://-error-.invalid/ http://-a.b.co http://a.b-.co http://0.0.0.0 http://10.1.1.0 http://10.1.1.1 http://10.1.1.125 http://10.1.1.254 http://10.1.1.255 http://10.255.255.255 http://172.16.0.0 http://172.16.0.1 http://172.16.0.254 http://172.16.0.255 http://172.16.125.0 http://172.16.125.1 http://172.16.125.254 http://172.16.125.255 http://172.16.255.0 http://172.16.255.1 http://172.16.255.125 http://172.16.255.254 http://172.16.255.255 http://172.24.0.0 http://172.24.0.1 http://172.24.0.254 http://172.24.0.255 http://172.24.125.0 http://172.24.125.1 http://172.24.125.254 http://172.24.125.255 http://172.24.255.0 http://172.24.255.1 http://172.24.255.125 http://172.24.255.254 http://172.24.255.255 http://172.31.0.0 http://172.31.0.1 http://172.31.0.254 http://172.31.0.255 http://172.31.125.0 http://172.31.125.1 http://172.31.125.254 http://172.31.125.255 http://172.31.255.0 http://172.31.255.1 http://172.31.255.125 http://172.31.255.254 http://172.31.255.255 http://192.168.1.0 http://192.168.1.1 http://192.168.1.125 http://192.168.1.254 http://192.168.1.255 http://192.168.255.0 http://192.168.255.1 http://192.168.255.125 http://192.168.255.254 http://192.168.255.255 http://224.1.1.1 new-value.1 http://123.123.123 http://3628126748 http://.www.foo.bar/ new-value./ http://.www.foo.bar./
      +http:// http://. http://.. http://../ http://? http://?? http://??/ http://# http://## http://##/ http://foo.bar?q=Spaces should be encoded // //a ///a /// http:///a foo.com rdar://1234 h://test http:// shouldfail.com :// should fail http://foo.bar/foo(bar)baz quux ftps://foo.bar/ http://-error-.invalid/ http://-a.b.co http://a.b-.co http://0.0.0.0 http://10.1.1.0 http://10.1.1.1 http://10.1.1.125 http://10.1.1.254 http://10.1.1.255 http://10.255.255.255 http://172.16.0.0 http://172.16.0.1 http://172.16.0.254 http://172.16.0.255 http://172.16.125.0 http://172.16.125.1 http://172.16.125.254 http://172.16.125.255 http://172.16.255.0 http://172.16.255.1 http://172.16.255.125 http://172.16.255.254 http://172.16.255.255 http://172.24.0.0 http://172.24.0.1 http://172.24.0.254 http://172.24.0.255 http://172.24.125.0 http://172.24.125.1 http://172.24.125.254 http://172.24.125.255 http://172.24.255.0 http://172.24.255.1 http://172.24.255.125 http://172.24.255.254 http://172.24.255.255 http://172.31.0.0 http://172.31.0.1 http://172.31.0.254 http://172.31.0.255 http://172.31.125.0 http://172.31.125.1 http://172.31.125.254 http://172.31.125.255 http://172.31.255.0 http://172.31.255.1 http://172.31.255.125 http://172.31.255.254 http://172.31.255.255 http://192.168.1.0 http://192.168.1.1 http://192.168.1.125 http://192.168.1.254 http://192.168.1.255 http://192.168.255.0 http://192.168.255.1 http://192.168.255.125 http://192.168.255.254 http://192.168.255.255 http://224.1.1.1 http://1.1.1.1.1 http://123.123.123 http://3628126748 http://.www.foo.bar/ http://www.foo.bar./ http://.www.foo.bar./

      at Context.<anonymous> (.test-build/tests/url-regexp.js:92:47)



[14:34:06] Plumber found unhandled error:
 Error in plugin 'gulp-mocha'
Message:
    6 tests failed.
----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
 src/           |    94.74 |       75 |      100 |    94.74 |                |
  url-regexp.js |    94.74 |       75 |      100 |    94.74 |             73 |
----------------|----------|----------|----------|----------|----------------|
All files       |    94.74 |       75 |      100 |    94.74 |                |
----------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 94.74% ( 18/19 )
Branches     : 75% ( 3/4 )
Functions    : 100% ( 4/4 )
Lines        : 94.74% ( 18/19 )
================================================================================
[14:34:06] Finished 'pragmatist:test-run' after 225 ms
[14:34:06] Starting 'pragmatist:test-clean'...
[14:34:06] Finished 'pragmatist:test-clean' after 4.92 ms
[14:34:06] Starting 'pragmatist:test'...
[14:34:06] Finished 'pragmatist:test' after 23 μs
curiosity:url-regexp gajus$

```

**Comment by gajus** [comment]
@renarsvilnis can you have a look at this?

I'd be happy to publish a new version if tests are not failing.

**Comment by renarsvilnis** [comment]
When I add options, that will solve the existing bugs, as they all rely on a single issue.

**Comment by gajus** [comment]
:+1:
